name: docs

on:
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install typst (PDF Builder)
        run: |
          wget -qO- https://github.com/typst/typst/releases/download/v0.11.0/typst-x86_64-unknown-linux-musl.tar.xz | tar -xJ
          sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/

      - name: Build docs
        uses: TinyTapeout/tt-docs-action@v1
