name: docs
on:
  push:
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docs
        uses: TinyTapeout/tt-gds-action/docs@main
