name: docs
on:
  push:
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build docs
        uses: docker://tinytapeout/tt-action:latest
        with:
          args: make docs
