name: gds
on:
  push:
  workflow_dispatch:
jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build GDS
        uses: tinytapeout/tt-gds-action@main
